# SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
# SPDX-License-Identifier: Apache-2.0

# Enable the Cortex-M7 caches, including when running from external flash.
CONFIG_CACHE_MANAGEMENT=y
